name: Main
on:
  push:
    branches: [ main, component-testing ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js                         
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Run npm ci
        run: npm ci
      - name: Patch Heroku
        run: heroku builds:cancel
      - name: install Heroku
        run: heroku git:remote -a pricing-options-app
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Test with Jest
        run: npm test -- -u

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          branch: main
