name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install --save mocha chai
      - name: Install dependencies 2 
        run: npm install --save request
      - name: Install dependencies 3 
        run: npm install --save express
      - name: Install dependencies 4
        run: npm install --save isomorphic-fetch
      - name: Install dependencies 5
        run: npm install --save dotenv
      - name: Run test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pricing-options-app"
          heroku_email: "alyssanewhart1@gmail.com"
